import { z } from "zod"
import { defineCapability } from "./helpers"

/**
 * People pillar — accounts, admins, roles, permissions, and per-user form
 * settings. Mirrors the `user:*`, `admin:*`, `role:*`, `permissions:*`,
 * `manageSabyUsers` and `*:user-form-settings` backend route permissions.
 */
export const peopleCapabilities = [
  defineCapability({
    name: "users.create",
    description: "Create a user account",
    category: "people",
    permissions: ["user:create"],
    riskLevel: "MEDIUM",
    inputSchema: z.object({
      fullName: z.string().describe("User display name"),
      email: z.string().email().describe("User email address"),
      phone: z.string().optional().describe("User phone number"),
      roleId: z.string().optional().describe("Initial role assignment"),
    }),
  }),
  defineCapability({
    name: "users.read",
    description: "Read user account and profile information",
    category: "people",
    permissions: ["user:read"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "users.update",
    description: "Update user account fields",
    category: "people",
    permissions: ["user:update"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "users.delete",
    description: "Delete a user account",
    category: "people",
    permissions: ["user:delete"],
    riskLevel: "CRITICAL",
  }),
  defineCapability({
    name: "users.deactivate",
    description: "Deactivate a user account",
    category: "people",
    permissions: ["user:update"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "users.reset_password",
    description: "Reset a user account password",
    category: "people",
    permissions: ["auth:resetPassword"],
    riskLevel: "CRITICAL",
  }),
  defineCapability({
    name: "users.import",
    description: "Bulk-import user accounts",
    category: "people",
    permissions: ["user:import"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "users.assign",
    description: "Assign roles, nodes, or workspaces to a user",
    category: "people",
    permissions: ["user:assign"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "users.restore",
    description: "Restore a deactivated or deleted user account",
    category: "people",
    permissions: ["user:restore"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "users.manage",
    description: "Manage tenant-level user configuration and membership",
    category: "people",
    permissions: ["user:manage"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "users.sabyManage",
    description: "Saby-operations waitlist and user administration",
    category: "people",
    permissions: ["manageSabyUsers"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "admins.create",
    description: "Create an administrator account",
    category: "people",
    permissions: ["admin:create"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "admins.read",
    description: "Read administrator account information",
    category: "people",
    permissions: ["admin:read"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "admins.update",
    description: "Update administrator account fields",
    category: "people",
    permissions: ["admin:update"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "admins.delete",
    description: "Delete an administrator account",
    category: "people",
    permissions: ["admin:delete"],
    riskLevel: "CRITICAL",
  }),
  defineCapability({
    name: "admins.assignRole",
    description: "Assign a role to an administrator account",
    category: "people",
    permissions: ["admin:assignRole"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "roles.create",
    description: "Create a role",
    category: "people",
    permissions: ["role:create"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "roles.read",
    description: "Read roles and their permission sets",
    category: "people",
    permissions: ["role:read"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "roles.update",
    description: "Update role fields",
    category: "people",
    permissions: ["role:update"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "roles.delete",
    description: "Delete a role",
    category: "people",
    permissions: ["role:delete"],
    riskLevel: "CRITICAL",
  }),
  defineCapability({
    name: "roles.permissions",
    description: "Manage the permission set attached to a role",
    category: "people",
    permissions: ["role:permissions"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "permissions.create",
    description: "Create a permission definition",
    category: "people",
    permissions: ["permissions:create"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "permissions.read",
    description: "Read permission definitions",
    category: "people",
    permissions: ["permissions:read"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "permissions.update",
    description: "Update a permission definition",
    category: "people",
    permissions: ["permissions:update"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "permissions.delete",
    description: "Delete a permission definition",
    category: "people",
    permissions: ["permissions:delete"],
    riskLevel: "CRITICAL",
  }),
  defineCapability({
    name: "userFormSettings.create",
    description: "Create per-user form display settings",
    category: "people",
    permissions: ["create:user-form-settings"],
    riskLevel: "LOW",
  }),
  defineCapability({
    name: "userFormSettings.read",
    description: "Read per-user form display settings",
    category: "people",
    permissions: ["view:user-form-settings", "view:user-form-settings::userId"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "userFormSettings.update",
    description: "Update per-user form display settings",
    category: "people",
    permissions: ["update:user-form-settings", "update:user-form-settings::userId"],
    riskLevel: "LOW",
  }),
  defineCapability({
    name: "userFormSettings.delete",
    description: "Delete per-user form display settings",
    category: "people",
    permissions: ["delete:user-form-settings", "delete:user-form-settings::userId"],
    riskLevel: "MEDIUM",
  }),
]