import { defineCapability } from "./helpers"

/**
 * Structure pillar — organizational nodes, departments, levels, and the
 * generic structures registry. Mirrors the `node:*`, `department:*`,
 * `level:*` and `structures:*` backend route permissions.
 */
export const structureCapabilities = [
  defineCapability({
    name: "nodes.create",
    description: "Create an organizational node (branch, office, unit)",
    category: "structure",
    permissions: ["node:create"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "nodes.read",
    description: "Read organizational node information",
    category: "structure",
    permissions: ["node:read"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "nodes.update",
    description: "Update node fields and memberships",
    category: "structure",
    permissions: ["node:update"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "nodes.delete",
    description: "Delete an organizational node",
    category: "structure",
    permissions: ["node:delete"],
    riskLevel: "CRITICAL",
  }),
  defineCapability({
    name: "nodes.import",
    description: "Bulk-import organizational nodes",
    category: "structure",
    permissions: ["node:import"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "nodes.move",
    description: "Move a node within the org hierarchy",
    category: "structure",
    permissions: ["node:move"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "nodes.activate",
    description: "Activate a node",
    category: "structure",
    permissions: ["node:activate"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "nodes.deactivate",
    description: "Deactivate a node",
    category: "structure",
    permissions: ["node:deactivate"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "nodes.manage",
    description: "Manage node-level configuration",
    category: "structure",
    permissions: ["node:manage"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "departments.create",
    description: "Create a department",
    category: "structure",
    permissions: ["department:create"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "departments.read",
    description: "Read department information",
    category: "structure",
    permissions: ["department:read"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "departments.update",
    description: "Update department fields",
    category: "structure",
    permissions: ["department:update"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "departments.delete",
    description: "Delete a department",
    category: "structure",
    permissions: ["department:delete"],
    riskLevel: "CRITICAL",
  }),
  defineCapability({
    name: "departments.import",
    description: "Bulk-import departments",
    category: "structure",
    permissions: ["import:department"],
    riskLevel: "HIGH",
  }),
  defineCapability({
    name: "departments.export",
    description: "Export department data",
    category: "structure",
    permissions: ["export:department"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "levels.create",
    description: "Create an org level in the hierarchy",
    category: "structure",
    permissions: ["level:create"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "levels.read",
    description: "Read org levels and hierarchy",
    category: "structure",
    permissions: ["level:read"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "levels.update",
    description: "Update an org level",
    category: "structure",
    permissions: ["level:update"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "levels.delete",
    description: "Delete an org level",
    category: "structure",
    permissions: ["level:delete"],
    riskLevel: "CRITICAL",
  }),
  defineCapability({
    name: "structures.create",
    description: "Create a structure record",
    category: "structure",
    permissions: ["structures:create"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "structures.read",
    description: "Read structure records",
    category: "structure",
    permissions: ["structures:read"],
    riskLevel: "LOW",
    idempotent: true,
  }),
  defineCapability({
    name: "structures.update",
    description: "Update a structure record",
    category: "structure",
    permissions: ["structures:update"],
    riskLevel: "MEDIUM",
  }),
  defineCapability({
    name: "structures.delete",
    description: "Delete a structure record",
    category: "structure",
    permissions: ["structures:delete"],
    riskLevel: "CRITICAL",
  }),
]